### PR TITLE
Fix typo on README page

### PR DESCRIPTION
**Pull request by HighCommander4**

### CODE REVIEW

**Comment by mickaelistria** [comment]
Please contribute to LSP4E via Gerrit.
I should probable delete this repo.


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by HighCommander4** [comment]
Is the README hosted somewhere else?

**Comment by mickaelistria** [comment]
The source of README is in the regular Git/Gerrit repo at Eclipse.org.

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by HighCommander4** [comment]
I'm aware of that. I was wondering if the rendered Markdown was hosted somewhere other than this Github.

**Comment by mickaelistria** [comment]
There's https://git.eclipse.org/r/plugins/gitiles/lsp4e/lsp4e/ where you can see a rendered README.md but the videos in it don't work (I don't know if there is a better way to do it with plain markdown...)

**Comment by HighCommander4** [comment]
Thanks. (The typo in question is already fixed in the eclipse.org repo.)

**Pull request closed without merging**
